### PR TITLE
Handle null argument in sendKeys

### PR DESCRIPTION
**Pull request by glib-briia**
Required for https://github.com/SeleniumHQ/selenium/pull/4418

### CODE REVIEW

**Comment by asashour** [comment]
Thanks, please note HtmlUnit-Driver follows Selenium, not the other way around.

**Comment by glib-briia** [comment]
Thank you. Just pushed another commit (0099c82ff7ba8507102f44d3e4bad25510043c78) to the same branch, fixing test. Could you please merge it as well.

**Comment by asashour** [comment]
Not sure how to merge it by the web interface.

Can you create a new PR?

**Comment by glib-briia** [comment]
Created #53. Thank you

**Pull request merged**
